[BUGFIX] init.d tomcat6 has a wrong JAVA_HOME
With Apache Solr 4.8 we need at least Java 7.
Iterates over possible java paths and sets the JAVA_HOME.

Resolves: #12346

Change-Id: Idc7ceda2d812560104286a72d0ac435862085e57
Reviewed-on: http://review.typo3.org/33619
Reviewed-by: Sascha Egerer <sascha@sascha-egerer.de>
Tested-by: Sascha Egerer <sascha@sascha-egerer.de>
Reviewed-by: Phuong Doan <phuong.doan@dkd.de>
Tested-by: Phuong Doan <phuong.doan@dkd.de>

diff --git a/Resources/Tomcat/tomcat6 b/Resources/Tomcat/tomcat6
--- a/Resources/Tomcat/tomcat6
+++ b/Resources/Tomcat/tomcat6
@@ -10,7 +10,32 @@
 # processname: tomcat
 ### END INIT INFO
 
-JAVA_HOME=/usr/lib/jvm/java-6-openjdk
+
+setJdk() {
+    JDK_DIRS="/usr/lib/jvm/java-7-openjdk /usr/lib/jvm/java-7-openjdk-i386 /usr/lib/jvm/java-7-openjdk-amd64"
+    for jdir in $JDK_DIRS; do
+        if [ -r "$jdir/bin/java" ]; then
+            JAVA_HOME="$jdir"
+            echo "JAVA_HOME has been automatically set to $JAVA_HOME"
+            break
+        fi
+    done
+
+    if [[ ! "$JAVA_HOME" = *"java-7"* ]]; then
+        echo "JAVA_HOME could not be set to Java 7. Please define JAVA_HOME manually."
+        exit 1
+    fi
+}
+
+if [ ! -z "$JAVA_HOME" ] && [[ ! "$JAVA_HOME" = *"java-7"* ]]; then
+    echo "JAVA_HOME is not set to Java 7. Searching now for JDK installation in default places..."
+    setJdk
+elif [ -z "$JAVA_HOME" ]; then
+    echo "JAVA_HOME has not been set. Searching now for JDK installation in default places..."
+    setJdk
+fi
+
+
 #JAVA_OPTS="$JAVA_OPTS -Dsolr.solr.home=/opt/solr-tomcat/solr"
 export JAVA_HOME
 #export JAVA_OPTS
