[TASK:11.2] equalize CI/Github-Actions for release-11.0|2|5 and main
Relates: #3465

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,6 +67,8 @@ jobs:
           echo -e "matrix : "
           echo $matrix
           echo ::set-output name=matrix::$(echo $matrix)
+          >&2 echo -e "Example Annotation on error. Is visible in Actions wokflow view."
+          >&2 echo -e "Non-stable releases can not be published to TER. The tag 11.5.0-beta-1 is invalid for TER."
       -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
@@ -169,7 +171,7 @@ jobs:
         run: |
           export CURRENT_TYPO3_VERSION_REFERNCE=$(./Build/Helpers/TYPO3_SOURCE_REFERENCE.sh "$TYPO3_VERSION" --short)
           export CURRENT_SOLARIUM_VERSION=$(cat composer.json | jq --raw-output '.require."solarium/solarium"')
-          export CI_CACHE_VERSION="2022.01.24@14:45"
+          export CI_CACHE_VERSION="2023.04.04@15:01"
           export CI_BUILD_CACHE_KEY=${{ runner.os }}-PHP:${{ matrix.PHP }}-TYPO3:$TYPO3_VERSION@$CURRENT_TYPO3_VERSION_REFERNCE-SOLARIUM:$CURRENT_SOLARIUM_VERSION-"CI_CACHE_VERSION:"$CI_CACHE_VERSION
           echo "COMPOSER_GLOBAL_REQUEREMENTS=$(composer config home)" >> $GITHUB_ENV
           echo "CI_BUILD_CACHE_KEY=$CI_BUILD_CACHE_KEY" >> $GITHUB_ENV
@@ -204,8 +206,8 @@ jobs:
       -
         name: Upload code coverage to Scrutinizer
         run: |
-          ocular code-coverage:upload --format=php-clover coverage.unit.clover
-          ocular code-coverage:upload --format=php-clover coverage.integration.clover
+          .Build/bin/ocular code-coverage:upload --format=php-clover coverage.unit.clover
+          .Build/bin/ocular code-coverage:upload --format=php-clover coverage.integration.clover
       -
         name: Clean up
         run: |
@@ -232,8 +234,9 @@ jobs:
         name: Check tag
         run: |
           TAGGED_VERSION=$(echo "${{ github.ref }}" | awk '{print tolower($0)}')
-          if ! [[ "$TAGGED_VERSION" =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}((-pre)?-(alpha|beta|rc)(-?[0-9]{1,3})?)?$ ]]; then
-            exit 1
+          if ! [[ "${TAGGED_VERSION}" =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}((-pre)?-(alpha|beta|rc)(-?[0-9]{1,3})?)?$ ]]; then
+            >&2 echo -e "Non-stable releases can not be published to TER. The tag ${TAGGED_VERSION} is invalid for TER."
+            exit 0
           fi
       -
         name: Resolve PHP version to use
@@ -262,7 +265,7 @@ jobs:
           echo "Following message will be printed in TER as release description:"
           echo -e "$TER_COMMENT"
           if ! composer extension-build; then
-            echo "Something went wrong on bulding EXT:solr for NON-Composer mode."
-            exit 1
+            >&2 echo -e "Something went wrong on bulding EXT:solr for NON-Composer mode. Please look in the job."
+            exit 13
           fi
           php ~/.composer/vendor/bin/tailor ter:publish --comment "$TER_COMMENT" "$RELEASE_VERSION"
