[TASK] Add proper annotations on GH actions job failures.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,6 +67,8 @@ jobs:
           echo -e "matrix : "
           echo $matrix
           echo ::set-output name=matrix::$(echo $matrix)
+          >&2 echo -e "Example Annotation on error. Is visible in Actions wokflow view."
+          >&2 echo -e "Non-stable releases can not be published to TER. The tag 11.5.0-beta-1 is invalid for TER."
       -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
@@ -232,8 +234,9 @@ jobs:
         name: Check tag
         run: |
           TAGGED_VERSION=$(echo "${{ github.ref }}" | awk '{print tolower($0)}')
-          if ! [[ "$TAGGED_VERSION" =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}((-pre)?-(alpha|beta|rc)(-?[0-9]{1,3})?)?$ ]]; then
-            exit 1
+          if ! [[ "${TAGGED_VERSION}" =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}((-pre)?-(alpha|beta|rc)(-?[0-9]{1,3})?)?$ ]]; then
+            >&2 echo -e "Non-stable releases can not be published to TER. The tag ${TAGGED_VERSION} is invalid for TER."
+            exit 0
           fi
       -
         name: Resolve PHP version to use
@@ -262,7 +265,7 @@ jobs:
           echo "Following message will be printed in TER as release description:"
           echo -e "$TER_COMMENT"
           if ! composer extension-build; then
-            echo "Something went wrong on bulding EXT:solr for NON-Composer mode."
-            exit 1
+            >&2 echo -e "Something went wrong on bulding EXT:solr for NON-Composer mode. Please look in the job."
+            exit 13
           fi
           php ~/.composer/vendor/bin/tailor ter:publish --comment "$TER_COMMENT" "$RELEASE_VERSION"
